# Generated by Django 5.0.7 on 2024-10-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_address_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_address',
            new_name='shopping_address',
        ),
    ]
