# Generated by Django 5.0.7 on 2024-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_shipping_address_product_shopping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(default=1, max_length=255, verbose_name='照片url'),
            preserve_default=False,
        ),
    ]
