# Generated by Django 5.0.7 on 2024-10-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productimage_image_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopping_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='发货地址'),
        ),
    ]
