# Generated by Django 5.0.7 on 2024-10-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, '未出售'), (2, '已出售'), (3, '已下架')], default=1, verbose_name='商品状态'),
        ),
    ]
