# Generated by Django 5.0.7 on 2024-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_user_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_status',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='是否特卖'),
        ),
    ]
