# Generated by Django 5.0.7 on 2024-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='under_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='降价后的价格'),
        ),
    ]
